# Generated by Django 2.2.4 on 2021-06-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField()),
                ('metadata', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'Sensor',
            },
        ),
    ]
