# Generated by Django 2.2.4 on 2021-06-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_sensor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table='Sensors',
        ),
    ]
