# Generated by Django 2.2.4 on 2021-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210605_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'Heartbeats',
            },
        ),
    ]
