# Generated by Django 2.2.4 on 2021-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_heartbeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeats',
            name='message',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
