# Generated by Django 2.2.4 on 2021-06-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_heartbeats_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ml_test',
        ),
    ]
