# Generated by Django 2.2.4 on 2021-06-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_delete_ml_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heartbeats',
            new_name='Heartbeat',
        ),
        migrations.AlterModelTable(
            name='heartbeat',
            table='Heartbeat',
        ),
    ]
