# Generated by Django 2.2.4 on 2021-06-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210605_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='state',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='serialNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
