# Generated by Django 2.2.4 on 2021-06-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20210606_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='message',
            field=models.IntegerField(),
        ),
    ]
