# Generated by Django 2.2.4 on 2021-06-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20210606_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='serialNumber',
        ),
        migrations.AddField(
            model_name='sensor',
            name='heartbeat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Heartbeat'),
            preserve_default=False,
        ),
    ]
