# Generated by Django 2.2.4 on 2021-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_sensor_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='heartbeat',
            field=models.ManyToManyField(to='database.Heartbeat'),
        ),
    ]
